# Generated by Django 5.2.8 on 2025-11-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('FOOD', 'Food'), ('TRAVEL', 'Travel'), ('BILLS', 'Bills'), ('SHOPPING', 'Shopping'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
